const translations = {
    en: {
        profession: "Backend Developer",
        name: "Andrii Fandieiev",
        description: "Determined and proactive. Continuous development — both intellectual and physical — is important to me. Alongside school, I completed a computer lyceum (Fortran, Pascal). My university diploma project was a software solution developed in Delphi. In my free time, I enjoy ice skating, swimming, and playing chess.",
        projects: "Pet Projects",
        experienceTitle: "Experience",
        educationTitle: "Education",
        techSkills: "Tech Skills",
        softSkills: "Soft Skills",
        contacts: "Contacts",
        wohnOrt: "Chemnitz.Germany",
        languages: "Languages",
        languag1: "German (B2)",
        languag2: "English (A2)",
        languag3: "Russian (native language)",
        languag4: "Ukrainian (native language)",
        Jetzt: "Backend Developer",
        JetztDetails1: "Teamwork on interesting project",
        JetztDetails2: "Finding balanced solutions and implementing them",
        JetztDetails3: "Unit and integration testing",
        company1: "Moving from Ukraine to Germany. Learning German and programming.",
        company1Details1: "German course B1. (benedict-school-sachsen.de)",
        company1Details2: "German course B2 - Vocational. (benedict-school-sachsen.de)",
        company1Details3: "Programming course. Tel-ran (tel-ran.de (Berlin))",
        company2: "Self-employed Entrepreneur",
        company2Details1: "Organization of sales channels",
        company2Details2: "Planning and organizing furniture production",
        company2Details3: "Development of new products and technological solutions",
        company3: "Head of Sales Department",
        company3Details1: "Sales planning",
        company3Details2: "Organization of product distribution channels",
        company3Details3: "Collection and analysis of statistical sales data",
        school1: "Kharkiv National University of Radio Electronics",
        speciality1: "Engineer (Biomedical equipment and systems)",
        school2: "Kharkiv Mechanical Engineering College",
        speciality2: "Business Administration (Part-time study)",
        school3: "Benedict School (Saxony)",
        speciality3: "German for Work B2",
        examDate: "Exam Date: 16.12.2023",
        school4: "Tel-ran (Berlin)",
        speciality4: "Backend Web Development (Online 960 hours)",
        educationPeriod1: "September 1993 - July 1998 | Ukraine",
        educationPeriod2: "September 1997 - December 1999 | Ukraine",
        educationPeriod3: "Exam Date: 16.12.2023 | Germany",
        educationPeriod4: "26.03.2024 - 10.03.2025 | Germany",
        JetztPeriod: "Jan 2025 - March 2025| Tel-ran Diplom Project",
        workPeriod1: "March 2022 - January 2025 - | Chemnitz, Germany",
        workPeriod2: "July 2007 - February 2022 | Ukraine",
        workPeriod3: "June 2001 - June 2005 | Ukraine"
    },
    de: {
        profession: "Backend Entwickler",
        name: "Andrii Fandieiev",
        description: "Entschlossen und initiativ. Ständige Weiterentwicklung — sowohl geistig als auch körperlich — ist mir wichtig. Parallel zur Schule habe ich ein Computerlyzeum abgeschlossen (Fortran, Pascal). Mein Diplomprojekt an der Universität war eine Softwarelösung in Delphi. In meiner Freizeit gehe ich eislaufen, schwimme und spiele Schach.",
        projects: "Pet Projects",
        experienceTitle: "Erfahrung",
        educationTitle: "Bildung",
        techSkills: "Technische Fähigkeiten",
        softSkills: "Soziale Kompetenzen",
        contacts: "Kontakte",
        wohnOrt: "Chemnitz.Deutschland",
        languages: "Sprachkenntnisse",
        languag1: "Deutsch (B2-Beruf)",
        languag2: "Englisch (A2)",
        languag3: "Russisch (Muttersprache)",
        languag4: "Ukrainisch (Muttersprache)",
        Jetzt: "Backend Entwickler",
        JetztDetails1: "Teamarbeit mit interessanten Projekten",
        JetztDetails2: "Suche nach ausgewogenen Lösungen und deren Umsetzung",
        JetztDetails3: "Unit - und Integrationstests",
        company1: "Umzug aus der Ukraine nach Deutschland. Lernen der deutschen Sprache und Programmierung.",
        company1Details1: "Deutsch kurs B1. (benedict-school-sachsen.de)",
        company1Details2: "Deutsch kurs B2-Beruf. (benedict-school-sachsen.de)",
        company1Details3: "Programmierung kurs. Tel-ran (tel-ran.de (Berlin))",
        company2: "Einzelunternehmer",
        company2Details1: "Organisation von Vertriebskanälen",
        company2Details2: "Planung und Organisation der Möbelproduktion",
        company2Details3: "Entwicklung neuer Produkte und technologischer Lösungen",
        company3: "Leiter der Verkaufsabteilung",
        company3Details1: "Absatzplanung",
        company3Details2: "Organisation von Produktvertriebskanälen",
        company3Details3: "Sammlung und Analyse statistischer Daten über den Umsatz",
        school1: "Charkiwer Nationale Universität für Radioelektronik",
        speciality1: "Ingenieur (Biomedizinische Geräte und Systeme)",
        school2: "Charkiwer Hochschule für Maschinenbau",
        speciality2: "Betriebswirtschaftslehre (Teilzeitstudium)",
        school3: "Benedict Schule (Sachsen)",
        speciality3: "Deutsch für den Beruf B2",
        examDate: "Prüfungsdatum: 16.12.2023",
        school4: "Tel-ran (Berlin)",
        speciality4: "Backend Webentwicklung (Online 960 Stunden)",
        educationPeriod1: "September 1993 - Juli 1998 | Ukraine",
        educationPeriod2: "September 1997 - Dezember 1999 | Ukraine",
        educationPeriod3: "Prüfungsdatum: 16.12.2023 | Deutschland",
        educationPeriod4: "26.03.2024 - 10.03.2025 | Deutschland",
        JetztPeriod: "Jan 2025 - März 2025| Tel-ran Diplom Project",
        workPeriod1: "März 2022 - Jan 2025 - | Chemnitz. Deutschland",
        workPeriod2: "Juli 2007 - Februar 2022 | Ukraine",
        workPeriod3: "Juni 2001 - Juni 2005 | Ukraine"
    },
    ru: {
        profession: "Backend разработчик",
        name: "Андрей Фандеев",
        description: "Решительный и инициативный.Для меня важно постоянное развитие — как умственное, так и физическое.Параллельно со школой я закончил компьютерный лицей(Фортран, Паскаль).Моим дипломным проектом в университете было программное решение на Delphi.В свободное время катаюсь на коньках, плаваю и играю в шахматы.",
        projects: "Проекты",
        experienceTitle: "Опыт работы",
        educationTitle: "Образование",
        techSkills: "Технические навыки",
        softSkills: "Софт-скиллы",
        contacts: "Контакты",
        wohnOrt: "Хемниц.Германия",
        languages: "Знание языков",
        languag1: "Немецкий (B2-проф)",
        languag2: "Английский (A2)",
        languag3: "Русский (родной)",
        languag4: "Украинский (родной)",
        Jetzt: "Backend разработчик",
        JetztDetails1: "Работа в команде над интересными проектами",
        JetztDetails2: "Поиск сбалансированных решений и их реализация",
        JetztDetails3: "Юнит- и интеграционное тестирование",
        company1: "Переезд из Украины в Германию. Изучение немецкого языка и программирования.",
        company1Details1: "Немецкий язык А1-А2-В1.(benedict-school-sachsen.de)",
        company1Details2: "Немецкий язык для профессии В2.(benedict-school-sachsen.de)",
        company1Details3: "Курсы программирования.Backend разработчик (tel-ran.de (Berlin))",
        company2: "Частный предприниматель",
        company2Details1: "Организация каналов сбыта",
        company2Details2: "Планирование и организация производства мебели",
        company2Details3: "Разработка новых продуктов и технологических решений",
        company3: "Руководитель отдела продаж",
        company3Details1: "Планирование продаж",
        company3Details2: "Организация каналов сбыта продукции",
        company3Details3: "Сбор и анализ статистических данных по продажам",
        school1: "Харьковский национальный университет радиоэлектроники",
        speciality1: "Инженер (Биомедицинское оборудование и системы)",
        school2: "Харьковский машиностроительный техникум",
        speciality2: "Бизнес-администрирование (заочное обучение)",
        school3: "Школа Benedict (Саксония)",
        speciality3: "Немецкий для работы B2",
        examDate: "Дата экзамена: 16.12.2023",
        school4: "Tel-ran (Берлин)",
        speciality4: "Backend веб-разработка (онлайн 960 часов)",
        educationPeriod1: "Сентябрь 1993 - Июль 1998 | Украина",
        educationPeriod2: "Сентябрь 1997 - Декабрь 1999 | Украина",
        educationPeriod3: "Дата экзамена: 16.12.2023 | Германия",
        educationPeriod4: "26.03.2024 - 10.03.2025 | Германия",
        JetztPeriod: "Янв 2025 - Март 2025| Tel-ran Германия (Дипломное проектирование)",
        workPeriod1: "Март 2022 - Янв 2025| Хемниц. Германия",
        workPeriod2: "Июль 2007 - Февр 2022 | Украина",
        workPeriod3: "Июнь 2001 - Июнь 2005 | Украина"
    }
};

document.querySelectorAll('[data-lang]').forEach(button => {
    button.addEventListener('click', () => {
        const lang = button.getAttribute('data-lang');
        changeLanguage(lang);
    });
});

function changeLanguage(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach(el => {
        const key = el.getAttribute('data-translate');
        if (translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });
    document.documentElement.lang = lang;
}